############################################################
# SCALE UP
# AUTOMATE UP-SCALE AND DOWN-SCALE
# UP-SCALE --> GUARANTEED IMPROVEMENT AND LONGER COMPUTATION (OTHERWISE COMPUTATIONBUG)
# CONSIDER HARDWARE OR DIFFERENT SOFTWARE (E.G. MANUAL DATA-PREPROCESSING)
############################################################

# SYSTEM INPUT/OUTPUT EXAMPLE
    # D2 LINK + D2 INPUT + D5 INPUT --> D5 OUTPUT (CONVOLUTED ENVIRONMENT)
    # NODE-COUNT LIMIT DEPENDING ON COMPUTER
    # PRE-TRAINED INTERNODE LINK, ON-CALL TRAINED NODE-LINK D2 (CLEAR ENVIRONMENT)
    # INTERNODE LINK PRETRAINED, AND REGULARLY UPDATED, AS VARIATION FOUND SMALL BETWEEN D2 D5 LINK SETS

# AUTOMATE UP-SCALE AND DOWN-SCALE: AUTOMATE NODE-GENERATION AND SYSTEM-EXTENSION/SHRINKAGE
# SYSTEM-EXTENSION/SHRINKAGE AND PARAMETER SETTINGS DEPENDING ON TRADE-OFF COMPUTATION-TIME AND PRECISION
# AUTOMATION GIVES MACHINE
# CLEAN CODE STYLE AFTER MACHINE
# VERSIONS COME AFTER 1 COMPLETION

############################################################
# NODE-GENERATION ##########################################
############################################################

# NODE-GENERATION <=> DATA-COLLECTION
# REQUIRES EXTERNAL DEVICE
# SIMULATE FOR DEMONSTRATION

